Models:
- Config: configs/body_2d_keypoint/topdown_regression/mpii/td-reg_res50_8xb64-210e_mpii-256x256.py
  In Collection: DeepPose
  Metadata:
    Architecture: &id001
    - DeepPose
    - ResNet
    Training Data: MPII
  Name: td-reg_res50_8xb64-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.826
      Mean@0.1: 0.18
    Task: Body 2D Keypoint
  Weights: httpxxx'
- Config: configs/body_2d_keypoint/topdown_regression/mpii/td-reg_res101_8xb64-210e_mpii-256x256.py
  In Collection: DeepPose
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: td-reg_res101_8xb64-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.841
      Mean@0.1: 0.2
    Task: Body 2D Keypoint
  Weights: httpxxx'
- Config: configs/body_2d_keypoint/topdown_regression/mpii/td-reg_res152_8xb64-210e_mpii-256x256.py
  In Collection: DeepPose
  Metadata:
    Architecture: *id001
    Training Data: MPII
  Name: td-reg_res152_8xb64-210e_mpii-256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.85
      Mean@0.1: 0.208
    Task: Body 2D Keypoint
  Weights: httpxxx'
