Collections:
- Name: SimpleBaseline3D
  Paper:
    Title: A simple yet effective baseline for 3d human pose estimation
    URL: httpxxx'
  README: httpxxx'
Models:
- Config: configs/body_3d_keypoint/image_pose_lift/h36m/image-pose-lift_tcn_8xb64-200e_h36m.py
  In Collection: SimpleBaseline3D
  Metadata:
    Architecture: &id001
    - SimpleBaseline3D
    Training Data: Human3.6M
  Name: image-pose-lift_tcn_8xb64-200e_h36m
  Results:
  - Dataset: Human3.6M
    Metrics:
      MPJPE: 43.4
      P-MPJPE: 34.3
    Task: Body 3D Keypoint
  Weights: httpxxx'
