Collections:
- Name: DSNT
  Paper:
    Title: Numerical Coordinate Regression with Convolutional Neural Networks
    URL: httpxxx'
  README: httpxxx'
Models:
- Config: configs/body_2d_keypoint/integral_regression/coco/ipr_res50_dsnt-8xb64-210e_coco-256x256.py
  In Collection: DSNT
  Metadata:
    Architecture: &id001
    - DSNT
    - ResNet
    Training Data: COCO
  Name: ipr_res50_dsnt-8xb64-210e_coco-256x256
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.674
      AP@0.5: 0.87
      AP@0.75: 0.744
      AR: 0.764
      AR@0.5: 0.928
    Task: Body 2D Keypoint
  Weights: httpxxx'
