Collections:
- Name: Wingloss
  Paper:
    Title: Wing Loss for Robust Facial Landmark Localisation with Convolutional Neural
      Networks
    URL: httpxxx'
  README: httpxxx'
Models:
- Config: configs/face_2d_keypoint/topdown_regression/wflw/td-reg_res50_wingloss_8xb64-210e_wflw-256x256.py
  In Collection: Wingloss
  Metadata:
    Architecture:
    - DeepPose
    - ResNet
    - WingLoss
    Training Data: WFLW
  Name: td-reg_res50_wingloss_8xb64-210e_wflw-256x256
  Results:
  - Dataset: WFLW
    Metrics:
      NME: 4.67
    Task: Face 2D Keypoint
  Weights: httpxxx'
